import 'package:dex_app/data/models/drug_model.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `drug_model.dart` with the code generated by Freezed
part 'cart_model.freezed.dart';
// optional: Since our CartModel class is serializable, we must add this line.
// But if CartModel was not serializable, we could skip it.
part 'cart_model.g.dart';

@freezed
class CartModel with _$CartModel {
  const factory CartModel({
    required DrugModel drugModel,
    required int quantity,
  }) = _CartModel;

  factory CartModel.fromJson(Map<String, Object?> json) =>
      _$CartModelFromJson(json);
}
