import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `drug_model.dart` with the code generated by Freezed
part 'drug_model.freezed.dart';
// optional: Since our DrugModel class is serializable, we must add this line.
// But if DrugModel was not serializable, we could skip it.
part 'drug_model.g.dart';

@freezed
class DrugModel with _$DrugModel {
  const factory DrugModel({
    required String firstName,
    required String lastName,
    required int age,
  }) = _DrugModel;

  factory DrugModel.fromJson(Map<String, Object?> json) =>
      _$DrugModelFromJson(json);
}
